#!/usr/bin/env sh

BAT_THEMES_DIR=$(bat --config-dir)/themes

if [[ ! -d $BAT_THEMES_DIR ]]; then
    echo "Making a new bat dir: $BAT_THEMES_DIR"
    mkdir -p $BAT_THEMES_DIR

    cd $BAT_THEMES_DIR
    # Download a theme in '.tmTheme' format, for example:
    git clone https://github.com/greggb/sublime-snazzy
    # get the Enki-Tokyo-Night theme
    wget https://raw.githubusercontent.com/enkia/enki-theme/master/scheme/Enki-Tokyo-Night.tmTheme

    # Update the binary cache
    bat cache --build
fi
