#!/usr/bin/env sh
# Initialize XDG base directory environment variables as defined in:
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html.
#
# Explicitly define them here so we don't need to add the additional code of
# handling the case where they are not explicitly defined, simplifying the code
# in the rest of our configurations which use XDG.

# Directory where user-specific data files should be stored.
export XDG_DATA_HOME="$HOME/.local/share"

# Preference-ordered set of base directories to search for data files in
# addition to the $XDG_DATA_HOME base directory.
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"

# Directory where user-specific configuration files should be stored.
export XDG_CONFIG_HOME="$HOME/.config"

# Preference-ordered set of base directories to search for configuration files
# in addition to the $XDG_CONFIG_HOME base directory.
#export XDG_CONFIG_DIRS="/etc/xdg"

# Directory where user-specific non-essential data files should be stored.
export XDG_CACHE_HOME="$HOME/.cache"

